
model:
  name: SGDClassifier
  framework: scikit-learn
  pipeline:
    steps:
      - name: StandardScaler
      - name: PCA
        params:
          n_components: 5
      - name: SGDClassifier
        params:
          random_state: 42
  hyperparameters:
    grid_search:
      pca__n_components: [4, 5]
      classifier__loss: ['hinge']
      classifier__alpha: [0.005, 0.03, 0.05]
      classifier__penalty: ['elasticnet']
  training:
    cv: 5
    scoring: recall
    n_jobs: -1
    verbose: 1
data:
  resampling:
    method: SMOTE
    params:
      random_state: 42
